### ISSUE TITLE
Removing ->withoutTime() from DateInput results in format() error

### ISSUE THREAD

**Issue by MACscr** [awcodes/trov-components#1]
```php
DateInput::make('opening_date')
    ->label('Opening Date'),
``` 

results in error `Call to a member function format() on string`.

Tried using `->format(app(GeneralSettings::class)->datetime_format)` like i would with the timepicker field and it yielded the same result.

If i keep ->withoutTime(), it doesnt seem to have a problem with the date provided. This field has a datetime cast.

**Comment by awcodes** [comment]
Hey Mark,

This is fixed with v0.1.6.

Also, you do not need to pass a format into the component. The Date and Datetime-local inputs only except a specific format of input, which the component takes care of. The display of the date is formatted based on the locale of the user's browser.

It looks like the pickers styles will probably still be less than desirable for you, but it might be an acceptable trade off if you'd prefer not to use a masked input.

Thanks for reporting the bug.
